---
repos:
  - hooks:
      - id: ruff
        args: [--select, I, --fix, src/http_utils]
      - id: ruff-format
        args: [src]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
